
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author cata
 */
public class ventanaDificil extends javax.swing.JFrame {

    /**
     * Creates new form ventanaDificil
     */
    ventanaSaludo vs = new ventanaSaludo();
    int contador = 0;
    int contador2 = 0;

    public ventanaDificil() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("APRENDAMOS LAS TABLAS");
        this.nombreDif.setText("VEAMOS QUE TAL TE VA CON LAS TABLAS...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreDif = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        numTablas3 = new javax.swing.JLabel();
        numTablas2 = new javax.swing.JLabel();
        numTablas5 = new javax.swing.JLabel();
        numTablas4 = new javax.swing.JLabel();
        numTablas6 = new javax.swing.JLabel();
        numTablas7 = new javax.swing.JLabel();
        numTablas10 = new javax.swing.JLabel();
        numTablas9 = new javax.swing.JLabel();
        panelTablas = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        numTablas1 = new javax.swing.JLabel();
        resp2 = new javax.swing.JTextField();
        resp1 = new javax.swing.JTextField();
        resp3 = new javax.swing.JTextField();
        resp5 = new javax.swing.JTextField();
        resp4 = new javax.swing.JTextField();
        resp6 = new javax.swing.JTextField();
        resp8 = new javax.swing.JTextField();
        resp7 = new javax.swing.JTextField();
        resp9 = new javax.swing.JTextField();
        resp10 = new javax.swing.JTextField();
        label11 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        label15 = new javax.swing.JLabel();
        label16 = new javax.swing.JLabel();
        label17 = new javax.swing.JLabel();
        label18 = new javax.swing.JLabel();
        label19 = new javax.swing.JLabel();
        label20 = new javax.swing.JLabel();
        numTablas8 = new javax.swing.JLabel();
        botonChequeo = new javax.swing.JButton();
        panelChequeo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        nombreDif.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombreDif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreDif.setText("VEAMOS QUE TAL TE VA CON LAS TABLAS...");

        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("1  ");

        label3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("3  ");

        label2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("2 ");

        label5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setText("5  ");

        label4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("4  ");

        label10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label10.setText("10  ");

        label9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label9.setText("9  ");

        label8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label8.setText("8  ");

        label7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label7.setText("7  ");

        label6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label6.setText("6  ");

        numTablas3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        numTablas2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        numTablas5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        numTablas4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        numTablas6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        numTablas7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        numTablas10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        numTablas9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        panelTablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA TABLA", " TABLA DEL 1", " TABLA DEL 2", " TABLA DEL 3", " TABLA DEL 4", " TABLA DEL 5", " TABLA DEL 6", " TABLA DEL 7", " TABLA DEL 8", " TABLA DEL 9", " TABLA DEL 10" }));
        panelTablas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                panelTablasItemStateChanged(evt);
            }
        });
        panelTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelTablasActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("ELEGI QUE TABLA QUERES PRACTICAR");

        numTablas1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        resp2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp2ActionPerformed(evt);
            }
        });

        resp1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp1ActionPerformed(evt);
            }
        });

        resp3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        resp5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        resp4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        resp6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        resp8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        resp7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        resp9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        resp10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        label11.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label11.setText("x");

        label12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label12.setText("x");

        label13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label13.setText("x");

        label14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label14.setText("x");

        label15.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label15.setText("x");

        label16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label16.setText("x");

        label17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label17.setText("x");

        label18.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("x");

        label19.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label19.setText("x");

        label20.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label20.setText("x");

        numTablas8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        botonChequeo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonChequeo.setText("CHEQUEAR RESPUESTAS CORRECTAS");
        botonChequeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonChequeoActionPerformed(evt);
            }
        });

        panelChequeo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        panelChequeo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("SALIR");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(botonChequeo)
                                .addGap(29, 29, 29)
                                .addComponent(panelChequeo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label9)
                                    .addComponent(label10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(numTablas10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(resp10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(numTablas9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(resp9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4)
                            .addComponent(label3)
                            .addComponent(label2)
                            .addComponent(label5))
                        .addGap(118, 118, 118)
                        .addComponent(resp5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numTablas6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resp6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(numTablas7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numTablas8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resp7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resp8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nombreDif, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(numTablas2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(numTablas3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(numTablas4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(numTablas5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(numTablas1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(15, 15, 15)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resp2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resp4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resp3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resp1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(panelTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreDif, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelTablas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonChequeo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numTablas4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(numTablas1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(label1)
                                                .addComponent(label11))
                                            .addComponent(resp1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(label2)
                                                .addComponent(label12))
                                            .addComponent(numTablas2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(label7)
                                                .addComponent(label17)
                                                .addComponent(resp2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(label3)
                                                .addComponent(label14))
                                            .addComponent(numTablas3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label13))))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(label5)
                                            .addComponent(label15))
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(numTablas5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(panelChequeo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(label6)
                                            .addComponent(label16)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resp6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numTablas6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(resp3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(resp4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(resp5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(numTablas7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(numTablas8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(label8)
                                                        .addComponent(label20))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(resp7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(resp8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(label18))
                                                    .addGap(7, 7, 7))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(numTablas9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(resp9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(7, 7, 7)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(label19)
                                                .addGap(8, 8, 8))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(resp10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(numTablas10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(30, 30, 30))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelTablasActionPerformed


    }//GEN-LAST:event_panelTablasActionPerformed

    private void panelTablasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_panelTablasItemStateChanged
        String numero = (String) panelTablas.getSelectedItem();
        if (numero.equals(" TABLA DEL 1")) {
            numTablas1.setText("1");
            numTablas2.setText("1");
            numTablas3.setText("1");
            numTablas4.setText("1");
            numTablas5.setText("1");
            numTablas6.setText("1");
            numTablas7.setText("1");
            numTablas8.setText("1");
            numTablas9.setText("1");
            numTablas10.setText("1");
        }
        if (numero.equals(" TABLA DEL 2")) {
            numTablas1.setText("2");
            numTablas2.setText("2");
            numTablas3.setText("2");
            numTablas4.setText("2");
            numTablas5.setText("2");
            numTablas6.setText("2");
            numTablas7.setText("2");
            numTablas8.setText("2");
            numTablas9.setText("2");
            numTablas10.setText("2");
        }
        if (numero.equals(" TABLA DEL 3")) {
            numTablas1.setText("3");
            numTablas2.setText("3");
            numTablas3.setText("3");
            numTablas4.setText("3");
            numTablas5.setText("3");
            numTablas6.setText("3");
            numTablas7.setText("3");
            numTablas8.setText("3");
            numTablas9.setText("3");
            numTablas10.setText("3");
        }
        if (numero.equals(" TABLA DEL 4")) {
            numTablas1.setText("4 =");
            numTablas2.setText("4 =");
            numTablas3.setText("4 =");
            numTablas4.setText("4 =");
            numTablas5.setText("4 =");
            numTablas6.setText("4 =");
            numTablas7.setText("4 =");
            numTablas8.setText("4 =");
            numTablas9.setText("4 =");
            numTablas10.setText("4 =");
        }
        if (numero.equals(" TABLA DEL 5")) {
            numTablas1.setText("5 =");
            numTablas2.setText("5 =");
            numTablas3.setText("5 =");
            numTablas4.setText("5 =");
            numTablas5.setText("5 =");
            numTablas6.setText("5 =");
            numTablas7.setText("5 =");
            numTablas8.setText("5 =");
            numTablas9.setText("5 =");
            numTablas10.setText("5 =");
        }
        if (numero.equals(" TABLA DEL 6")) {
            numTablas1.setText("6 =");
            numTablas2.setText("6 =");
            numTablas3.setText("6 =");
            numTablas4.setText("6 =");
            numTablas5.setText("6 =");
            numTablas6.setText("6 =");
            numTablas7.setText("6 =");
            numTablas8.setText("6 =");
            numTablas9.setText("6 =");
            numTablas10.setText("6 =");
        }
        if (numero.equals(" TABLA DEL 7")) {
            numTablas1.setText("7 =");
            numTablas2.setText("7 =");
            numTablas3.setText("7 =");
            numTablas4.setText("7 =");
            numTablas5.setText("7 =");
            numTablas6.setText("7 =");
            numTablas7.setText("7 =");
            numTablas8.setText("7 =");
            numTablas9.setText("7 =");
            numTablas10.setText("7 =");
        }
        if (numero.equals(" TABLA DEL 8")) {
            numTablas1.setText("8 =");
            numTablas2.setText("8 =");
            numTablas3.setText("8 =");
            numTablas4.setText("8 =");
            numTablas5.setText("8 =");
            numTablas6.setText("8 =");
            numTablas7.setText("8 =");
            numTablas8.setText("8 =");
            numTablas9.setText("8 =");
            numTablas10.setText("8 =");
        }
        if (numero.equals(" TABLA DEL 9")) {
            numTablas1.setText("9 =");
            numTablas2.setText("9 =");
            numTablas3.setText("9 =");
            numTablas4.setText("9 =");
            numTablas5.setText("9 =");
            numTablas6.setText("9 =");
            numTablas7.setText("9 =");
            numTablas8.setText("9 =");
            numTablas9.setText("9 =");
            numTablas10.setText("9 =");
        }
        if (numero.equals(" TABLA DEL 10")) {
            numTablas1.setText("10 =");
            numTablas2.setText("10 =");
            numTablas3.setText("10 =");
            numTablas4.setText("10 =");
            numTablas5.setText("10 =");
            numTablas6.setText("10 =");
            numTablas7.setText("10 =");
            numTablas8.setText("10 =");
            numTablas9.setText("10 =");
            numTablas10.setText("10 =");
        }
    }//GEN-LAST:event_panelTablasItemStateChanged

    private void resp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp1ActionPerformed


    }//GEN-LAST:event_resp1ActionPerformed

    private void resp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp2ActionPerformed


    }//GEN-LAST:event_resp2ActionPerformed

    private void botonChequeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonChequeoActionPerformed
        int numero1 = Integer.valueOf(label1.getText().trim());
        int numero2 = Integer.valueOf(label2.getText().trim());
        int numero3 = Integer.valueOf(label3.getText().trim());
        int numero4 = Integer.valueOf(label4.getText().trim());
        int numero5 = Integer.valueOf(label5.getText().trim());
        int numero6 = Integer.valueOf(label6.getText().trim());
        int numero7 = Integer.valueOf(label7.getText().trim());
        int numero8 = Integer.valueOf(label8.getText().trim());
        int numero9 = Integer.valueOf(label9.getText().trim());
        int numero10 = Integer.valueOf(label10.getText().trim());

        if (panelTablas.getSelectedItem().equals(" TABLA DEL 1")) {

            int result1 = numero1 * 1;
            int result2 = numero2 * 1;
            int result3 = numero3 * 1;
            int result4 = numero4 * 1;
            int result5 = numero5 * 1;
            int result6 = numero6 * 1;
            int result7 = numero7 * 1;
            int result8 = numero8 * 1;
            int result9 = numero9 * 1;
            int result10 = numero10 * 1;
            String resu1 = String.valueOf(result1);
            String resu2 = String.valueOf(result2);
            String resu3 = String.valueOf(result3);
            String resu4 = String.valueOf(result4);
            String resu5 = String.valueOf(result5);
            String resu6 = String.valueOf(result6);
            String resu7 = String.valueOf(result7);
            String resu8 = String.valueOf(result8);
            String resu9 = String.valueOf(result9);
            String resu10 = String.valueOf(result10);
            if (resu1.equals(resp1.getText().trim())) {
                contador++;
            }
            if (resu2.equals(resp2.getText().trim())) {
                contador++;
            }
            if (resu3.equals(resp3.getText().trim())) {
                contador++;
            }
            if (resu4.equals(resp4.getText().trim())) {
                contador++;
            }
            if (resu5.equals(resp5.getText().trim())) {
                contador++;
            }
            if (resu6.equals(resp6.getText().trim())) {
                contador++;
            }
            if (resu7.equals(resp7.getText().trim())) {
                contador++;
            }
            if (resu8.equals(resp8.getText().trim())) {
                contador++;
            }
            if (resu9.equals(resp9.getText().trim())) {
                contador++;
            }
            if (resu10.equals(resp10.getText().trim())) {
                contador++;
            }

            String conta = String.valueOf(contador);
            this.panelChequeo.setText(conta);
            this.botonChequeo.setEnabled(false);
        }
        if (panelTablas.getSelectedItem().equals(" TABLA DEL 2")) {
            int result12 = numero1 * 2;
            int result22 = numero2 * 2;
            int result32 = numero3 * 2;
            int result42 = numero4 * 2;
            int result52 = numero5 * 2;
            int result62 = numero6 * 2;
            int result72 = numero7 * 2;
            int result82 = numero8 * 2;
            int result92 = numero9 * 2;
            int result102 = numero10 * 2;
            String resu12 = String.valueOf(result12);
            String resu22 = String.valueOf(result22);
            String resu32 = String.valueOf(result32);
            String resu42 = String.valueOf(result42);
            String resu52 = String.valueOf(result52);
            String resu62 = String.valueOf(result62);
            String resu72 = String.valueOf(result72);
            String resu82 = String.valueOf(result82);
            String resu92 = String.valueOf(result92);
            String resu102 = String.valueOf(result102);
            if (resu12.equals(resp1.getText().trim())) {
                contador++;
            }
            if (resu22.equals(resp2.getText().trim())) {
                contador++;
            }
            if (resu32.equals(resp3.getText().trim())) {
                contador++;
            }
            if (resu42.equals(resp4.getText().trim())) {
                contador++;
            }
            if (resu52.equals(resp5.getText().trim())) {
                contador++;
            }
            if (resu62.equals(resp6.getText().trim())) {
                contador++;
            }
            if (resu72.equals(resp7.getText().trim())) {
                contador++;
            }
            if (resu82.equals(resp8.getText().trim())) {
                contador++;
            }
            if (resu92.equals(resp9.getText().trim())) {
                contador++;
            }
            if (resu102.equals(resp10.getText().trim())) {
                contador++;
            }
            String conta = String.valueOf(contador);
            this.panelChequeo.setText(conta);
            this.botonChequeo.setEnabled(false);

        }
        if (panelTablas.getSelectedItem().equals(" TABLA DEL 3")) {
            int result12 = numero1 * 3;
            int result22 = numero2 * 3;
            int result32 = numero3 * 3;
            int result42 = numero4 * 3;
            int result52 = numero5 * 3;
            int result62 = numero6 * 3;
            int result72 = numero7 * 3;
            int result82 = numero8 * 3;
            int result92 = numero9 * 3;
            int result102 = numero10 * 3;
            String resu12 = String.valueOf(result12);
            String resu22 = String.valueOf(result22);
            String resu32 = String.valueOf(result32);
            String resu42 = String.valueOf(result42);
            String resu52 = String.valueOf(result52);
            String resu62 = String.valueOf(result62);
            String resu72 = String.valueOf(result72);
            String resu82 = String.valueOf(result82);
            String resu92 = String.valueOf(result92);
            String resu102 = String.valueOf(result102);
            if (resu12.equals(resp1.getText().trim())) {
                contador++;
            }
            if (resu22.equals(resp2.getText().trim())) {
                contador++;
            }
            if (resu32.equals(resp3.getText().trim())) {
                contador++;
            }
            if (resu42.equals(resp4.getText().trim())) {
                contador++;
            }
            if (resu52.equals(resp5.getText().trim())) {
                contador++;
            }
            if (resu62.equals(resp6.getText().trim())) {
                contador++;
            }
            if (resu72.equals(resp7.getText().trim())) {
                contador++;
            }
            if (resu82.equals(resp8.getText().trim())) {
                contador++;
            }
            if (resu92.equals(resp9.getText().trim())) {
                contador++;
            }
            if (resu102.equals(resp10.getText().trim())) {
                contador++;
            }
            String conta = String.valueOf(contador);
            this.panelChequeo.setText(conta);
            this.botonChequeo.setEnabled(false);

        }
        if (panelTablas.getSelectedItem().equals(" TABLA DEL 4")) {
            int result12 = numero1 * 4;
            int result22 = numero2 * 4;
            int result32 = numero3 * 4;
            int result42 = numero4 * 4;
            int result52 = numero5 * 4;
            int result62 = numero6 * 4;
            int result72 = numero7 * 4;
            int result82 = numero8 * 4;
            int result92 = numero9 * 4;
            int result102 = numero10 * 4;
            String resu12 = String.valueOf(result12);
            String resu22 = String.valueOf(result22);
            String resu32 = String.valueOf(result32);
            String resu42 = String.valueOf(result42);
            String resu52 = String.valueOf(result52);
            String resu62 = String.valueOf(result62);
            String resu72 = String.valueOf(result72);
            String resu82 = String.valueOf(result82);
            String resu92 = String.valueOf(result92);
            String resu102 = String.valueOf(result102);
            if (resu12.equals(resp1.getText().trim())) {
                contador++;
            }
            if (resu22.equals(resp2.getText().trim())) {
                contador++;
            }
            if (resu32.equals(resp3.getText().trim())) {
                contador++;
            }
            if (resu42.equals(resp4.getText().trim())) {
                contador++;
            }
            if (resu52.equals(resp5.getText().trim())) {
                contador++;
            }
            if (resu62.equals(resp6.getText().trim())) {
                contador++;
            }
            if (resu72.equals(resp7.getText().trim())) {
                contador++;
            }
            if (resu82.equals(resp8.getText().trim())) {
                contador++;
            }
            if (resu92.equals(resp9.getText().trim())) {
                contador++;
            }
            if (resu102.equals(resp10.getText().trim())) {
                contador++;
            }
            String conta = String.valueOf(contador);
            this.panelChequeo.setText(conta);
            this.botonChequeo.setEnabled(false);

        }
        if (panelTablas.getSelectedItem().equals(" TABLA DEL 5")) {
            int result12 = numero1 * 5;
            int result22 = numero2 * 5;
            int result32 = numero3 * 5;
            int result42 = numero4 * 5;
            int result52 = numero5 * 5;
            int result62 = numero6 * 5;
            int result72 = numero7 * 5;
            int result82 = numero8 * 5;
            int result92 = numero9 * 5;
            int result102 = numero10 * 5;
            String resu12 = String.valueOf(result12);
            String resu22 = String.valueOf(result22);
            String resu32 = String.valueOf(result32);
            String resu42 = String.valueOf(result42);
            String resu52 = String.valueOf(result52);
            String resu62 = String.valueOf(result62);
            String resu72 = String.valueOf(result72);
            String resu82 = String.valueOf(result82);
            String resu92 = String.valueOf(result92);
            String resu102 = String.valueOf(result102);
            if (resu12.equals(resp1.getText().trim())) {
                contador++;
            }
            if (resu22.equals(resp2.getText().trim())) {
                contador++;
            }
            if (resu32.equals(resp3.getText().trim())) {
                contador++;
            }
            if (resu42.equals(resp4.getText().trim())) {
                contador++;
            }
            if (resu52.equals(resp5.getText().trim())) {
                contador++;
            }
            if (resu62.equals(resp6.getText().trim())) {
                contador++;
            }
            if (resu72.equals(resp7.getText().trim())) {
                contador++;
            }
            if (resu82.equals(resp8.getText().trim())) {
                contador++;
            }
            if (resu92.equals(resp9.getText().trim())) {
                contador++;
            }
            if (resu102.equals(resp10.getText().trim())) {
                contador++;
            }
            String conta = String.valueOf(contador);
            this.panelChequeo.setText(conta);
            this.botonChequeo.setEnabled(false);

        }
        if (panelTablas.getSelectedItem().equals(" TABLA DEL 6")) {
            int result12 = numero1 * 6;
            int result22 = numero2 * 6;
            int result32 = numero3 * 6;
            int result42 = numero4 * 6;
            int result52 = numero5 * 6;
            int result62 = numero6 * 6;
            int result72 = numero7 * 6;
            int result82 = numero8 * 6;
            int result92 = numero9 * 6;
            int result102 = numero10 * 6;
            String resu12 = String.valueOf(result12);
            String resu22 = String.valueOf(result22);
            String resu32 = String.valueOf(result32);
            String resu42 = String.valueOf(result42);
            String resu52 = String.valueOf(result52);
            String resu62 = String.valueOf(result62);
            String resu72 = String.valueOf(result72);
            String resu82 = String.valueOf(result82);
            String resu92 = String.valueOf(result92);
            String resu102 = String.valueOf(result102);
            if (resu12.equals(resp1.getText().trim())) {
                contador++;
            }
            if (resu22.equals(resp2.getText().trim())) {
                contador++;
            }
            if (resu32.equals(resp3.getText().trim())) {
                contador++;
            }
            if (resu42.equals(resp4.getText().trim())) {
                contador++;
            }
            if (resu52.equals(resp5.getText().trim())) {
                contador++;
            }
            if (resu62.equals(resp6.getText().trim())) {
                contador++;
            }
            if (resu72.equals(resp7.getText().trim())) {
                contador++;
            }
            if (resu82.equals(resp8.getText().trim())) {
                contador++;
            }
            if (resu92.equals(resp9.getText().trim())) {
                contador++;
            }
            if (resu102.equals(resp10.getText().trim())) {
                contador++;
            }
            String conta = String.valueOf(contador);
            this.panelChequeo.setText(conta);
            this.botonChequeo.setEnabled(false);

        }
        if (panelTablas.getSelectedItem().equals(" TABLA DEL 7")) {
            int result12 = numero1 * 7;
            int result22 = numero2 * 7;
            int result32 = numero3 * 7;
            int result42 = numero4 * 7;
            int result52 = numero5 * 7;
            int result62 = numero6 * 7;
            int result72 = numero7 * 7;
            int result82 = numero8 * 7;
            int result92 = numero9 * 7;
            int result102 = numero10 * 7;
            String resu12 = String.valueOf(result12);
            String resu22 = String.valueOf(result22);
            String resu32 = String.valueOf(result32);
            String resu42 = String.valueOf(result42);
            String resu52 = String.valueOf(result52);
            String resu62 = String.valueOf(result62);
            String resu72 = String.valueOf(result72);
            String resu82 = String.valueOf(result82);
            String resu92 = String.valueOf(result92);
            String resu102 = String.valueOf(result102);
            if (resu12.equals(resp1.getText().trim())) {
                contador++;
            }
            if (resu22.equals(resp2.getText().trim())) {
                contador++;
            }
            if (resu32.equals(resp3.getText().trim())) {
                contador++;
            }
            if (resu42.equals(resp4.getText().trim())) {
                contador++;
            }
            if (resu52.equals(resp5.getText().trim())) {
                contador++;
            }
            if (resu62.equals(resp6.getText().trim())) {
                contador++;
            }
            if (resu72.equals(resp7.getText().trim())) {
                contador++;
            }
            if (resu82.equals(resp8.getText().trim())) {
                contador++;
            }
            if (resu92.equals(resp9.getText().trim())) {
                contador++;
            }
            if (resu102.equals(resp10.getText().trim())) {
                contador++;
            }
            String conta = String.valueOf(contador);
            this.panelChequeo.setText(conta);
            this.botonChequeo.setEnabled(false);

        }
        if (panelTablas.getSelectedItem().equals(" TABLA DEL 8")) {
            int result12 = numero1 * 8;
            int result22 = numero2 * 8;
            int result32 = numero3 * 8;
            int result42 = numero4 * 8;
            int result52 = numero5 * 8;
            int result62 = numero6 * 8;
            int result72 = numero7 * 8;
            int result82 = numero8 * 8;
            int result92 = numero9 * 8;
            int result102 = numero10 * 8;
            String resu12 = String.valueOf(result12);
            String resu22 = String.valueOf(result22);
            String resu32 = String.valueOf(result32);
            String resu42 = String.valueOf(result42);
            String resu52 = String.valueOf(result52);
            String resu62 = String.valueOf(result62);
            String resu72 = String.valueOf(result72);
            String resu82 = String.valueOf(result82);
            String resu92 = String.valueOf(result92);
            String resu102 = String.valueOf(result102);
            if (resu12.equals(resp1.getText().trim())) {
                contador++;
            }
            if (resu22.equals(resp2.getText().trim())) {
                contador++;
            }
            if (resu32.equals(resp3.getText().trim())) {
                contador++;
            }
            if (resu42.equals(resp4.getText().trim())) {
                contador++;
            }
            if (resu52.equals(resp5.getText().trim())) {
                contador++;
            }
            if (resu62.equals(resp6.getText().trim())) {
                contador++;
            }
            if (resu72.equals(resp7.getText().trim())) {
                contador++;
            }
            if (resu82.equals(resp8.getText().trim())) {
                contador++;
            }
            if (resu92.equals(resp9.getText().trim())) {
                contador++;
            }
            if (resu102.equals(resp10.getText().trim())) {
                contador++;
            }
            String conta = String.valueOf(contador);
            this.panelChequeo.setText(conta);
            this.botonChequeo.setEnabled(false);

        }
        if (panelTablas.getSelectedItem().equals(" TABLA DEL 9")) {
            int result12 = numero1 * 9;
            int result22 = numero2 * 9;
            int result32 = numero3 * 9;
            int result42 = numero4 * 9;
            int result52 = numero5 * 9;
            int result62 = numero6 * 9;
            int result72 = numero7 * 9;
            int result82 = numero8 * 9;
            int result92 = numero9 * 9;
            int result102 = numero10 * 9;
            String resu12 = String.valueOf(result12);
            String resu22 = String.valueOf(result22);
            String resu32 = String.valueOf(result32);
            String resu42 = String.valueOf(result42);
            String resu52 = String.valueOf(result52);
            String resu62 = String.valueOf(result62);
            String resu72 = String.valueOf(result72);
            String resu82 = String.valueOf(result82);
            String resu92 = String.valueOf(result92);
            String resu102 = String.valueOf(result102);
            if (resu12.equals(resp1.getText().trim())) {
                contador++;
            }
            if (resu22.equals(resp2.getText().trim())) {
                contador++;
            }
            if (resu32.equals(resp3.getText().trim())) {
                contador++;
            }
            if (resu42.equals(resp4.getText().trim())) {
                contador++;
            }
            if (resu52.equals(resp5.getText().trim())) {
                contador++;
            }
            if (resu62.equals(resp6.getText().trim())) {
                contador++;
            }
            if (resu72.equals(resp7.getText().trim())) {
                contador++;
            }
            if (resu82.equals(resp8.getText().trim())) {
                contador++;
            }
            if (resu92.equals(resp9.getText().trim())) {
                contador++;
            }
            if (resu102.equals(resp10.getText().trim())) {
                contador++;
            }
            String conta = String.valueOf(contador);
            this.panelChequeo.setText(conta);
            this.botonChequeo.setEnabled(false);

        }
        if (panelTablas.getSelectedItem().equals(" TABLA DEL 10")) {
            int result12 = numero1 * 10;
            int result22 = numero2 * 10;
            int result32 = numero3 * 10;
            int result42 = numero4 * 10;
            int result52 = numero5 * 10;
            int result62 = numero6 * 10;
            int result72 = numero7 * 10;
            int result82 = numero8 * 10;
            int result92 = numero9 * 10;
            int result102 = numero10 * 10;
            String resu12 = String.valueOf(result12);
            String resu22 = String.valueOf(result22);
            String resu32 = String.valueOf(result32);
            String resu42 = String.valueOf(result42);
            String resu52 = String.valueOf(result52);
            String resu62 = String.valueOf(result62);
            String resu72 = String.valueOf(result72);
            String resu82 = String.valueOf(result82);
            String resu92 = String.valueOf(result92);
            String resu102 = String.valueOf(result102);
            if (resu12.equals(resp1.getText().trim())) {
                contador++;
            }
            if (resu22.equals(resp2.getText().trim())) {
                contador++;
            }
            if (resu32.equals(resp3.getText().trim())) {
                contador++;
            }
            if (resu42.equals(resp4.getText().trim())) {
                contador++;
            }
            if (resu52.equals(resp5.getText().trim())) {
                contador++;
            }
            if (resu62.equals(resp6.getText().trim())) {
                contador++;
            }
            if (resu72.equals(resp7.getText().trim())) {
                contador++;
            }
            if (resu82.equals(resp8.getText().trim())) {
                contador++;
            }
            if (resu92.equals(resp9.getText().trim())) {
                contador++;
            }
            if (resu102.equals(resp10.getText().trim())) {
                contador++;
            }
            String conta = String.valueOf(contador);
            this.panelChequeo.setText(conta);
            this.botonChequeo.setEnabled(false);

        }
        if (panelTablas.getSelectedItem().equals("SELECCIONA UNA TABLA")) {
            JOptionPane.showMessageDialog(null, "SELECCIONA UNA TABLA PARA EMPEZAR");
        }
        
        if (panelChequeo.getText().trim().equals("0") ||panelChequeo.getText().trim().equals("1") || panelChequeo.getText().trim().equals("2") || panelChequeo.getText().trim().equals("3")
                || panelChequeo.getText().trim().equals("4") || panelChequeo.getText().trim().equals("5") || panelChequeo.getText().trim().equals("6")) {
            JOptionPane.showMessageDialog(null, "Tuviste menos de 7 respuestas correctas... DESAPROBADO!","",JOptionPane.ERROR_MESSAGE);
            panelChequeo.setForeground(Color.red);
        } else if (panelChequeo.getText().trim().equals("7")) {
            JOptionPane.showMessageDialog(null, "Acertaste 7 respuestas. De milagro pero...APROBASTE!");
            panelChequeo.setForeground(Color.cyan);
        } else if(panelChequeo.getText().trim().equals("8")||panelChequeo.getText().trim().equals("9")
                ||panelChequeo.getText().trim().equals("10")){
            JOptionPane.showMessageDialog(null, "ACERTASTE MAS DE 7 RESPUESTAS. SOS UNA GENIA!!!!");
            panelChequeo.setForeground(Color.GREEN);
        }


    }//GEN-LAST:event_botonChequeoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        resp1.setText("");
        resp2.setText("");
        resp3.setText("");
        resp4.setText("");
        resp5.setText("");
        resp6.setText("");
        resp7.setText("");
        resp8.setText("");
        resp9.setText("");
        resp10.setText("");
        panelChequeo.setText("");
        panelTablas.setSelectedItem("SELECCIONA UNA TABLA");
        botonChequeo.setEnabled(true);
        contador = 0;

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ventanaDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ventanaDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ventanaDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ventanaDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ventanaDificil().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonChequeo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label18;
    private javax.swing.JLabel label19;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label20;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    public static javax.swing.JLabel nombreDif;
    private javax.swing.JLabel numTablas1;
    private javax.swing.JLabel numTablas10;
    private javax.swing.JLabel numTablas2;
    private javax.swing.JLabel numTablas3;
    private javax.swing.JLabel numTablas4;
    private javax.swing.JLabel numTablas5;
    private javax.swing.JLabel numTablas6;
    private javax.swing.JLabel numTablas7;
    private javax.swing.JLabel numTablas8;
    private javax.swing.JLabel numTablas9;
    private javax.swing.JLabel panelChequeo;
    private javax.swing.JComboBox<String> panelTablas;
    private javax.swing.JTextField resp1;
    private javax.swing.JTextField resp10;
    private javax.swing.JTextField resp2;
    private javax.swing.JTextField resp3;
    private javax.swing.JTextField resp4;
    private javax.swing.JTextField resp5;
    private javax.swing.JTextField resp6;
    private javax.swing.JTextField resp7;
    private javax.swing.JTextField resp8;
    private javax.swing.JTextField resp9;
    // End of variables declaration//GEN-END:variables
}
